Fix exploit of bot auto confirming
Gelbpunkt/IdleRPG pull request #220
Opened 2019-09-03 10:07 UTC by CHamburr

The reaction that the bot adds to the message triggers the listener and the bot thinks that it confirmed.

2019-09-03 10:09 UTC, CHamburr commented
Also, a guy with id 340440443302969344 got $134,000 from this exploit so please remove their money!!!

2019-09-03 13:17 UTC, numbermaniac requested changes

2019-09-03 13:17 UTC, numbermaniac commented on classes/context.py
> +            return false
In Python the word is `False`, not `false`.

2019-09-03 13:22 UTC, numbermaniac commented
Maybe a change should also be made somewhere around [here](https://github.com/Gelbpunkt/IdleRPG/blob/v4/cogs/trading/__init__.py#L239-L244) to prevent users offering items to any bot.

2019-09-03 13:23 UTC, Gelbpunkt commented
Or just delete the Bot's account :P

2019-09-03 13:24 UTC, numbermaniac commented
oh no

2019-09-03 13:31 UTC, CHamburr commented
God sorry I was dumb

2019-09-13 18:12 UTC, maxx0911 commented
Not sure if you forgot about this but this bug still is in the bot.

2019-09-14 10:45 UTC, merged